server:
  port: 8070
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #????????? config server ???????????????? ? ?????? eureka
    fetchRegistry: false  #?????? ??????????? ?????????? ?? ???????
    serviceUrl:
      defaultZone:
        http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 5